# version: '3' # Bỏ comment nếu Docker yêu cầu

services:
  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: noteurgoals_nginx_dev
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - app-network

  # Vite Dev Server for Development
  vite:
    image: node:18-alpine
    container_name: noteurgoals_vite
    working_dir: /var/www
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - app-network

  # PHP Application Service
  app:
    container_name: app_dev
    build: 
      context: ./php
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    environment:
      - APP_NAME=NoteurGoals Backend
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=s103d190-u2.interdata.vn
      - DB_PORT=3306
      - DB_DATABASE=NoteManegementSystem
      - DB_USERNAME=noteurgo
      - DB_PASSWORD=b29oWG7)Ve]Ve8
      - VITE_DEV_SERVER_URL=http://localhost:5173
      # Thêm các biến môi trường cho Pusher và Queue
      - BROADCAST_DRIVER=pusher
      - QUEUE_CONNECTION=database
      - PUSHER_APP_ID=2034146
      - PUSHER_APP_KEY=3e7a2a337ce61ab42859
      - PUSHER_APP_SECRET=d94a724d187ede0033e9
      - PUSHER_APP_CLUSTER=ap1
    networks:
      - app-network

  # === THÊM MỚI SERVICE WORKER CHO MÔI TRƯỜNG DEV ===
  worker:
    container_name: worker_dev
    # Sử dụng lại cấu hình build của service 'app'
    build:
      context: ./php
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./src:/var/www
    # Ghi đè lệnh mặc định để chạy queue worker
    command: "php artisan queue:work --verbose --tries=3 --timeout=90"
    working_dir: /var/www
    environment:
      # Worker cũng cần các biến môi trường này
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=s103d190-u2.interdata.vn
      - DB_PORT=3306
      - DB_DATABASE=NoteManegementSystem
      - DB_USERNAME=noteurgo
      - DB_PASSWORD=b29oWG7)Ve]Ve8
      - BROADCAST_DRIVER=pusher
      - QUEUE_CONNECTION=database
      - PUSHER_APP_ID=2034146
      - PUSHER_APP_KEY=3e7a2a337ce61ab42859
      - PUSHER_APP_SECRET=d94a724d187ede0033e9
      - PUSHER_APP_CLUSTER=ap1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge