
#version: '3'

services:
  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: noteurgoals_nginx_dev
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - app-network

  # Vite Dev Server for Development
  vite:
    image: node:18-alpine
    container_name: noteurgoals_vite
    working_dir: /var/www
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - app-network

  # PHP Application Service
  app:
    container_name: app_dev
    build: 
      context: ./php
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    environment:
      - APP_NAME=NoteurGoals Backend
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=s103d190-u2.interdata.vn
      - DB_PORT=3306
      - DB_DATABASE=NoteManegementSystem
      - DB_USERNAME=noteurgo
      - DB_PASSWORD=b29oWG7)Ve]Ve8
      - VITE_DEV_SERVER_URL=http://localhost:5173
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 