version: '3.8' # Bỏ comment và sử dụng phiên bản mới nhất để có các tính năng tốt hơn

services:
  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: noteurgoals_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - app-network

  # PHP Application Service
  app:
    container_name: app
    build: 
      # === SỬA LỖI Ở ĐÂY ===
      # Đặt context là thư mục gốc (.) để Docker thấy được cả thư mục 'src' và 'php'
      context: .
      # Chỉ rõ đường dẫn đến Dockerfile từ context gốc
      dockerfile: ./php/Dockerfile
      # =====================
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    environment:
      - APP_NAME=NoteurGoals Backend
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=s103d190-u2.interdata.vn
      - DB_PORT=3306
      - DB_DATABASE=NoteManegementSystem
      - DB_USERNAME=noteurgo
      - DB_PASSWORD=b29oWG7)Ve]Ve8
      - BROADCAST_DRIVER=pusher
      - QUEUE_CONNECTION=database
      - PUSHER_APP_ID=2034146
      - PUSHER_APP_KEY=3e7a2a337ce61ab42859
      - PUSHER_APP_SECRET=d94a724d187ede0033e9
      - PUSHER_APP_CLUSTER=ap1
    networks:
      - app-network

  # Queue Worker Service
  worker:
    container_name: worker
    build:
      # === SỬA LỖI Ở ĐÂY (TƯƠNG TỰ NHƯ SERVICE 'APP') ===
      context: .
      dockerfile: ./php/Dockerfile
      # ==================================================
    restart: unless-stopped
    volumes:
      - ./src:/var/www
    command: "php artisan queue:work --sleep=3 --tries=3"
    working_dir: /var/www
    environment:
      # Worker cũng cần các biến môi trường này
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=s103d190-u2.interdata.vn
      - DB_PORT=3306
      - DB_DATABASE=NoteManegementSystem
      - DB_USERNAME=noteurgo
      - DB_PASSWORD=b29oWG7)Ve]Ve8
      - BROADCAST_DRIVER=pusher
      - QUEUE_CONNECTION=database
      - PUSHER_APP_ID=2034146
      - PUSHER_APP_KEY=3e7a2a337ce61ab42859
      - PUSHER_APP_SECRET=d94a724d187ede0033e9
      - PUSHER_APP_CLUSTER=ap1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge