version: '3.8'

services:
  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app

  # Application Service
  app:
    container_name: blog
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: s103d190-u2.interdata.vn
      DB_PORT: 3306
      DB_DATABASE: NoteManegementSystem
      DB_USERNAME: noteurgo
      DB_PASSWORD: b29oWG7)Ve]Ve8
