# version: '3'

services:
  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: noteurgoals_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - app-network

  # PHP Application Service
  app:
    container_name: app
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    environment:
      - APP_NAME=NoteurGoals Backend
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=s103d190-u2.interdata.vn
      - DB_PORT=3306
      - DB_DATABASE=NoteManegementSystem
      - DB_USERNAME=noteurgo
      - DB_PASSWORD=b29oWG7)Ve]Ve8
    networks:
      - app-network

networks:
  app-network:
    driver: bridge